import type { CollectionConfig } from 'payload'

export const SeoSettings: CollectionConfig = {
  slug: 'seo-settings',
  admin: {
    useAsTitle: 'site_title',
  },
  fields: [
    { name: 'site_title', type: 'text', required: true, defaultValue: 'Pola Dashboard' },
    { name: 'site_description', type: 'textarea' },
    { name: 'site_keywords', type: 'textarea' },
    { name: 'site_author', type: 'text' },
    { name: 'site_language', type: 'text', defaultValue: 'en' },
    { name: 'default_title', type: 'text' },
    { name: 'default_description', type: 'textarea' },
    { name: 'default_keywords', type: 'textarea' },
    { name: 'title_separator', type: 'text', defaultValue: '|' },
    { name: 'title_template', type: 'text', defaultValue: '{page_title} {separator} {site_title}' },
    { name: 'og_site_name', type: 'text' },
    { name: 'og_default_image_url', type: 'text' },
    { name: 'og_default_type', type: 'text', defaultValue: 'website' },
    { name: 'og_locale', type: 'text', defaultValue: 'en_US' },
    { name: 'twitter_site', type: 'text' },
    { name: 'twitter_creator', type: 'text' },
    { name: 'twitter_card_type', type: 'text', defaultValue: 'summary_large_image' },
    { name: 'organization_schema', type: 'json' },
    { name: 'website_schema', type: 'json' },
    { name: 'breadcrumb_schema', type: 'json' },
    { name: 'canonical_url', type: 'text' },
    { name: 'robots_txt_content', type: 'textarea' },
    { name: 'sitemap_enabled', type: 'checkbox', defaultValue: true },
    { name: 'sitemap_priority', type: 'number', defaultValue: 0.8 },
    { name: 'sitemap_changefreq', type: 'text', defaultValue: 'weekly' },
    { name: 'google_analytics_id', type: 'text' },
    { name: 'google_search_console_verification', type: 'text' },
    { name: 'google_tag_manager_id', type: 'text' },
    { name: 'facebook_pixel_id', type: 'text' },
    { name: 'bing_webmaster_verification', type: 'text' },
    { name: 'enable_gzip', type: 'checkbox', defaultValue: true },
    { name: 'enable_minification', type: 'checkbox', defaultValue: true },
    { name: 'enable_caching', type: 'checkbox', defaultValue: true },
    { name: 'cache_duration', type: 'number', defaultValue: 3600 },
    { name: 'facebook_url', type: 'text' },
    { name: 'twitter_url', type: 'text' },
    { name: 'linkedin_url', type: 'text' },
    { name: 'instagram_url', type: 'text' },
    { name: 'youtube_url', type: 'text' },
    { name: 'contact_email', type: 'email' },
    { name: 'contact_phone', type: 'text' },
    { name: 'business_address', type: 'textarea' },
    { name: 'business_city', type: 'text' },
    { name: 'business_state', type: 'text' },
    { name: 'business_country', type: 'text' },
    { name: 'business_postal_code', type: 'text' },
    { name: 'last_seo_check', type: 'date' },
    { name: 'seo_score', type: 'number', defaultValue: 0 },
    { name: 'seo_issues_list', type: 'json' },
    { name: 'is_active', type: 'checkbox', defaultValue: true },
  ],
}
